# Generated by Django 5.0.6 on 2024-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_repayment', '0002_rename_amount_loanrepayment_amountp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='amountp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=255, max_length=50),
        ),
    ]
