# Generated by Django 5.0.6 on 2024-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idnumber',
            field=models.DecimalField(db_index=True, decimal_places=0, default=0, max_digits=15, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, max_length=255),
        ),
    ]
