"""
Django settings for woni project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y#r=sd6haqvk79p)l&gg+knt(bg1snjq%)*_nq&qe+&nfi$7vo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
AUTH_USER_MODEL = "authentication.User"
LOGIN_URL = "/authentication/login"



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'buyshares',
    'loan_application',
    'loan_repayment',
    'loans',
    'shares',
    'django_daraja'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'woni.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'woni.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':"django.db.backends.postgresql",
        'NAME':"woni-app",
        'USER':"postgres" , 
        'PASSWORD':"pass",
        'DB_HOST':"localhost",
        'DB_PORT':5432
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [os.path.join(BASE_DIR,'woni/static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# The Mpesa environment to use
# Possible values: sandbox, production
MPESA_ENVIRONMENT = 'sandbox'
# Credentials for the daraja app
MPESA_CONSUMER_KEY = 'K0GjqVP6USGncRvlAbvUIhXpVGdrQQ2C8nzJB90CdtI4swAl'
MPESA_CONSUMER_SECRET = 'srotRXasPuxrIYlxMEcCcuO5gHTGEvuLx2HJ3rMmgADkGeWGbcBT6UJXO2V9P8dG'
#Shortcode to use for transactions. For sandbox  use the Shortcode 1 provided on test credentials page
MPESA_SHORTCODE = '174379'
# Shortcode to use for Lipa na MPESA Online (MPESA Express) transactions
MPESA_EXPRESS_SHORTCODE = '174379'
# Type of shortcode
MPESA_SHORTCODE_TYPE = 'paybill'
# Lipa na MPESA Online passkey
MPESA_PASSKEY = 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
# Username for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)
MPESA_INITIATOR_USERNAME = 'testapi'
# Plaintext password for initiator (to be used in B2C, B2B, AccountBalance and TransactionStatusQuery Transactions)
MPESA_INITIATOR_SECURITY_CREDENTIAL = 'P44V3y+iBZukU4n2RsrgB4+ynK47NySpgAxvxI/VXA87gQP4oV5P634Loiwd2sjpxK/7hzuhIChGSTNi6/DJWQcty23Gc2e1D4AgbpixWmmaQe2HnPNDGMCoc3Gv6mWFEgjOM0LnkEejiRkl++5a4zZt4r4+0KHlFu9Be+tVCwttKppWo49ZZ4e7Sl0lsGhkJTQJGXHqJ9IXF66/rye0u+d5NAf56jCZ/Rc/D9WQLo060L1VcGdkQ26Q+FeEQy+nqCM3w9iXLhE8jS3dtJW0qlBjtHp/w4/InVoHXlfrbECV+SBX2ATDEJXJ14HA0tClTIEcZ3++QC7fwN3YAEmH/w=='