# Generated by Django 5.0.6 on 2024-06-10 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_borrowed', models.DecimalField(decimal_places=2, max_digits=255, max_length=50)),
                ('loan_balance', models.DecimalField(decimal_places=2, max_digits=255, max_length=50)),
                ('date_borrowed', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('due_Date', models.DateTimeField()),
                ('loan_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
