# Generated by Django 5.0.6 on 2024-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='due_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
